### ISSUE TITLE
Doesn't work in gnome 3.26

### ISSUE THREAD

**Issue by mpkh** [zpydr/gnome-shell-extension-taskbar#160]
Aug 21 12:47:29 Belial gnome-shell-ext[14281]: JS WARNING: [/home/ccc/.local/share/gnome-shell/extensions/TaskBar@zpydr/prefs.js 115]: Too many arguments to method Gtk.Notebook.popup_enable: expected 0, got 1
Aug 21 12:48:46 Belial gnome-shell[2359]: JS WARNING: [/home/ccc/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js 802]: reference to undefined property "Util"
Aug 21 12:48:46 Belial gnome-shell[2359]: Extension "TaskBar@zpydr" had error: TypeError: Main.Util is undefined
Aug 21 12:48:51 Belial gnome-shell[2359]: JS WARNING: [/home/ccc/.local/share/gnome-shell/extensions/TaskBar@zpydr/extension.js 802]: reference to undefined property "Util"
Aug 21 12:48:51 Belial gnome-shell[2359]: Extension "TaskBar@zpydr" had error: TypeError: Main.Util is undefined

**Comment by lsatenstein** [comment]
Does not work with btrfs file system and 3.22, 3,24

**Comment by lsatenstein** [comment]
Just got a beta 3.26 version of Gnome.  With ext4 file system, Taskbar settings cause a crash to gnome-shell 3.26
If I enable favorites, or move left/right of the workspace#, destop,task, or set a color for active/inactive task.

That suggests a disable/enable problem (I have been learning your code)
as well, adding a space between  active/inactive tasks and the rest goes wild  
I want 24 pixals, but get a lockup and on restart, its 360 pixals.  Definitely not what I was  aiming for.

**Comment by Taz8du29** [comment]
Which distribution? I'm on ubuntu 17.10, with gnome-shell 3.26.1 ad all works fine !

**Comment by mpkh** [comment]
I think this issue is obsolete

**Comment by lsatenstein** [comment]
As of 9 October, 2017 and Gnome 3.26, TaskBar@zpydr works for me two ways
as ~/.local/share/gnome-shell/extensions/Taskbar@zpydr 
and
/usr/share/gnome-shell/extensions/Taskbar@zpydr 
with compiled /usr/share/glib2.0/schemas/org.gnome.shell.extensions.TaskBar.gschema.xml
 
(different Linux versions)
